version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    image: ${DOCKERHUB_USERNAME}/strugl
    environment:
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
    volumes:
      - static:/static
    depends_on:
      - db
  enginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/${USER}/nginx/letsencrypt:/etc/letsencrypt
      - /home/${USER}/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
volumes: 
     pgdata:
