version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=testingdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: server
    environment:
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes: 
     pgdata: